### ISSUE TITLE
MPGA: Not Implemented Error

### ISSUE THREAD

**Issue by mjiggidy** [markreidvfx/pyavb#11]
I am getting a `NotImplementedError: b'MPGA'` python error while calling `avb.core.walk_references()` on a particular `BinItem`, which is a `CMPO` type for a `SourceMob` of an AMA'd clip (did I get that right? 😃).

Full output is below.  The first line (`Walking <b'CMPO'...>`) is from me; the rest is from the error:

```python
Walking <b'CMPO' avb.trackgroups.Composition ARC DE TRIOMPHE-9iGCOO2iV7s SourceMob len: 38976 urn:smpte:umid:060a2b34.01010100.01010f00.13000000.06cdc00e.12308b9c.9dfdbd92.013e89ee at 0x112090140>
b'MPGA'
b'4147504d70000000020301acde070000abde0700010141100000004d58a087facaf5419a68f0cadefdbb71010348aade0700020348920600fcff7813190400000000000002010200100044ac0000000000ecff020000001b00000000000000000001014d880500000000000001024d400800000000000003'
Traceback (most recent call last):
  File "/Users/editor/dev/pyavb1.0/mj/look.py", line 80, in <module>
    main()
  File "/Users/editor/dev/pyavb1.0/mj/look.py", line 75, in main
    seq, mobs = compare_bin(file_bin.content)
  File "/Users/editor/dev/pyavb1.0/mj/look.py", line 11, in compare_bin
    refs = list(avb.core.walk_references(mob))
  File "/Users/editor/dev/pyavb1.0/lib/python3.10/site-packages/pyavb-1.1.0.dev1-py3.10.egg/avb/core.py", line 147, in walk_references
  File "/Users/editor/dev/pyavb1.0/lib/python3.10/site-packages/pyavb-1.1.0.dev1-py3.10.egg/avb/core.py", line 137, in walk_references
  File "/Users/editor/dev/pyavb1.0/lib/python3.10/site-packages/pyavb-1.1.0.dev1-py3.10.egg/avb/utils.py", line 27, in value
  File "/Users/editor/dev/pyavb1.0/lib/python3.10/site-packages/pyavb-1.1.0.dev1-py3.10.egg/avb/file.py", line 318, in read_object
NotImplementedError: b'MPGA'
```

I believe `MPGA` is an `MPEGAudioDescriptor`

Example bin with this problem is attached:
[mpga.avb.zip](https://github.com/markreidvfx/pyavb/files/9013702/mpga.avb.zip)
.

Other info:
- Avid: 2021.12.2
- OS: MacOS Mojave
- Python: 3.10
- MediaInfo from AMA'd clip:

```
General
Complete name                            : /Users/editor/Desktop/JARDIN DU LUXEMBOURG-cFjJ3uY3e_U.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 142 MiB
Duration                                 : 7 min 15 s
Overall bit rate                         : 2 734 kb/s
Writing application                      : Google
gsst                                     : 0
gstd                                     : 435630

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 1 frame
Format settings, GOP                     : M=1, N=60
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 7 min 15 s
Bit rate                                 : 2 604 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.113
Stream size                              : 135 MiB (95%)
Title                                    : ISO Media file produced by Google Inc.
Writing library                          : x264 core 155 r2901 7d0ff22
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 7 min 15 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 6.65 MiB (5%)
Title                                    : ISO Media file produced by Google Inc.
Language                                 : English
```

Please let me know if you need any other info! Thank you!

**Comment by markreidvfx** [comment]
Thanks for the bin sample, that is really all that is needed in most cases . Yes looks like a MediaFileDescriptor haven't seen before, should be pretty straight forward to add. 

```
<AvClass id="MPGA">
  <AvProp id="MDES" name="OMFI:MDES:MobKind" type="char">1</AvProp>
  <AvProp id="MDES" name="OMFI:MDES:MC:Intermediate" type="Boolean">FALSE</AvProp>
  <AvProp id="MDES" name="OMFI:AMDL:acfUID" tag="1" type="bytes">16 4d 58 a0 87 fa ca f5 41 9a 68 f0 ca de fd bb 71 </AvProp>
  <AvProp id="MDFL" name="EdRate.mantissa" type="int32">430664</AvProp>
  <AvProp id="MDFL" name="EdRate.exp10" type="int16">-4</AvProp>
  <AvProp id="MDFL" name="OMFI:MDFL:Length" type="int32">19212072</AvProp>
  <AvProp id="MDFL" name="OMFI:MDFL:IsOMFI" type="int16">0</AvProp>
  <AvProp id="MDFL" name="OMFI:MDFL:dataOffset" type="int32">0</AvProp>
  <AvProp id="MPGA" name="OMFI:MDAU:NumChannels" type="uint16">2d</AvProp>
  <AvProp id="MPGA" name="OMFI:MDAU:BitsPerSample" type="uint16">16d</AvProp>
  <AvProp id="MPGA" name="EdRate.mantissa" type="int32">44100</AvProp>
  <AvProp id="MPGA" name="EdRate.exp10" type="int16">0</AvProp>
  <AvProp id="MPGA" name="OMFI:MDAU:Locked" type="Boolean">FALSE</AvProp>
  <AvProp id="MPGA" name="OMFI:MDAU:AudioRefLevel" type="int16">-20</AvProp>
  <AvProp id="MPGA" name="OMFI:MDAU:ElectroSpatialFormulation" type="int32">2</AvProp>
  <AvProp id="MPGA" name="OMFI:MDAU:DialNorm" type="uint16">27d</AvProp>
  <AvProp id="MPGA" name="OMFI:MDAU:AudioCodingFormat" type="int32">0</AvProp>
  <AvProp id="MPGA" name="OMFI:MPGA:BitRate" type="uint32">0d</AvProp>
  <AvProp id="MPGA" name="OMFI:MPGA:SubframeAlignment" tag="1" type="uint64">1416</AvProp>
  <AvProp id="MPGA" name="OMFI:MPGA:Origin" tag="2" type="uint64">2112</AvProp>
  <AvProp id="MDES" name="OMFI:MDES:Locator" tag="2" type="reference">
    <AvClass id="MSML">
      <AvProp id="MSML" name="MobID.high" type="int32">-1184293039</AvProp>
      <AvProp id="MSML" name="MobID.low" type="int32">-65982094</AvProp>
      <AvProp id="MSML" name="OMFI:MSML:LastKnownVolume" type="string">Macintosh HD</AvProp>
      <AvProp id="MSML" name="OMFI:MSML:DomainType" tag="1" type="int32">0</AvProp>
      <AvProp id="MSML" name="MobID.SMPTELabel" tag="2" type="bytes">12 6 a 2b 34 1 1 1 0 1 1 f 0 </AvProp>
      <AvProp id="MSML" name="MobID.length" tag="2" type="uchar">19</AvProp>
      <AvProp id="MSML" name="MobID.instanceHigh" tag="2" type="uchar">0</AvProp>
      <AvProp id="MSML" name="MobID.instanceMid" tag="2" type="uchar">0</AvProp>
      <AvProp id="MSML" name="MobID.instanceLow" tag="2" type="uchar">0</AvProp>
      <AvProp id="MSML" name="MobID.material.Data1" tag="2" type="uint32">3110674257d</AvProp>
      <AvProp id="MSML" name="MobID.material.Data2" tag="2" type="uint16">12658d</AvProp>
      <AvProp id="MSML" name="MobID.material.Data3" tag="2" type="uint16">64529d</AvProp>
      <AvProp id="MSML" name="MobID.material.Data4" tag="2" type="bytes">8 a5 25 7c 48 13 fd 1d c2 </AvProp>
      <AvProp id="MSML" name="OMFI:MSML:LastKnownVolumeUTF8" tag="3" type="UTF8string">Macintosh HD</AvProp>
    </AvClass>
  </AvProp>
  <AvProp id="MDES" name="OMFI:MOBJ:PhysicalMedia" tag="3" type="reference">
    <AvClass id="MDES">
      <AvProp id="MDES" name="OMFI:MDES:MobKind" type="char">1</AvProp>
      <AvProp id="MDES" name="OMFI:MDES:MC:Intermediate" type="Boolean">FALSE</AvProp>
      <AvProp id="MDES" name="OMFI:AMDL:acfUID" tag="1" type="bytes">16 4d 58 a0 87 fa ca f5 41 9a 68 f0 ca de fd bb 71 </AvProp>
      <AvProp id="MDES" name="OMFI:MDES:Locator" tag="1" type="reference">
        <AvClass id="WINF">
          <AvProp id="WINF" name="OMFI:FL:PathName" type="string">//Users//editor//Desktop//JARDIN DU LUXEMBOURG-cFjJ3uY3e_U.mp4</AvProp>
          <AvProp id="WINF" name="OMFI:FL:PathNameUTF8" tag="2" type="UTF8string">//Users//editor//Desktop//JARDIN DU LUXEMBOURG-cFjJ3uY3e_U.mp4</AvProp>
        </AvClass>
      </AvProp>
      <AvProp id="MDES" name="OMFI:MOBJ:PhysicalMedia" tag="2" type="reference"/>
    </AvClass>
  </AvProp>
  <AvProp id="MDES" name="OMFI:AMDL:Attributes" tag="2" type="reference">
    <AvClass id="ATTR">
      <AvProp id="ATTR" name="__OMFI:ATTR:NumItems" type="int32">3</AvProp>
      <List id="OMFI:ATTR:AttrRefs">
        <ListElem>
          <AvProp id="ATTR" name="OMFI:ATTB:Kind" type="int32">4</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:Name" type="string">_CONTAINER_HANDLER_GUID</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:BobSize" type="int32">16</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:BobData" type="bytes">16 73 dc 6 3c 76 2 4c 4c ba 3f 3f 47 12 c d1 e9 </AvProp>
        </ListElem>
        <ListElem>
          <AvProp id="ATTR" name="OMFI:ATTB:Kind" type="int32">4</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:Name" type="string">SoundEssenceCoding</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:BobSize" type="int32">16</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:BobData" type="bytes">16 6 e 2b 34 4 1 1 d 4 2 2 2 4 4 1 0 </AvProp>
        </ListElem>
        <ListElem>
          <AvProp id="ATTR" name="OMFI:ATTB:Kind" type="int32">4</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:Name" type="string">_AMD_SOURCE_LENGTH</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:BobSize" type="int32">8</AvProp>
          <AvProp id="ATTR" name="OMFI:ATTB:BobData" type="bytes">8 28 27 25 1 0 0 0 0 </AvProp>
        </ListElem>
        <ListElem/>
      </List>
    </AvClass>
  </AvProp>
</AvClass>
```

**Comment by markreidvfx** [comment]
Added in e40757a92efe2c2758ed1897a6b946e366a068bd. Give it a go when you get a chance.

**Comment by mjiggidy** [comment]
It is working for me!  That was fast; thank you so much!
